image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - cd functions
    - npm install -g firebase-tools
    # - npm install -g bower
    - npm install
    # - bower install --allow-root
    - firebase use --token 1/dVV0AEESEJaZFd1CLRd3hXrQCkBphUSrCzQ6n3ZoI_c production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token 1/dVV0AEESEJaZFd1CLRd3hXrQCkBphUSrCzQ6n3ZoI_c
